spring:
  datasource:
    url: 'jdbc:h2:file:./bank-db'
    username: 'user'
    password: 'pass'
  jpa.hibernate.ddl-auto: create

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
